[package]
name = "switch-album-sorter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.44.0"
clap = "4.0.32"
serde_json = "1.0.91"
walkdir = "2.3.2"
